<?php

add_action(
	'init',
	function () {
		$to_register = array(
			array( '/archives', 'render_block_core_archives' ),
			array( '/avatar', 'render_block_core_avatar' ),
			array( '/block', 'render_block_core_block' ),
			array( '/categories', 'render_block_core_categories' ),
			array( '/comment-author-name', 'render_block_core_comment_author_name' ),
			array( '/comment-content', 'render_block_core_comment_content' ),
			array( '/comment-date', 'render_block_core_comment_date' ),
			array( '/comment-edit-link', 'render_block_core_comment_edit_link' ),
			array( '/comment-reply-link', 'render_block_core_comment_reply_link' ),
			array( '/cover', 'render_block_core_cover' ),
			array( '/heading', 'block_core_heading_render' ),
			array( '/loginout', 'render_block_core_loginout' ),
			array( '/post-author', 'render_block_core_post_author' ),
			array( '/post-author-biography', 'render_block_core_post_author_biography' ),
			array( '/post-author-name', 'render_block_core_post_author_name' ),
			array( '/post-content', 'render_block_core_post_content' ),
			array( '/post-date', 'render_block_core_post_date' ),
			array( '/pattern', 'render_block_core_pattern' ),
			array( '/post-navigation-link', 'render_block_core_post_navigation_link' ),
			array( '/post-title', 'render_block_core_post_title' ),
			array( '/query-no-results', 'render_block_core_query_no_results' ),
			array( '/query-pagination', 'render_block_core_query_pagination' ),
			array( '/query-pagination-next', 'render_block_core_query_pagination_next' ),
			array( '/query-pagination-numbers', 'render_block_core_query_pagination_numbers' ),
			array( '/query-pagination-previous', 'render_block_core_query_pagination_previous' ),
			array( '/read-more', 'render_block_core_read_more' ),
			array( '/rss', 'render_block_core_rss' ),
			array( '/site-tagline', 'render_block_core_site_tagline' ),
			array( '/site-title', 'render_block_core_site_title' ),
			array( '/tag-cloud', 'render_block_core_tag_cloud' ),
		);

		foreach ( $to_register as list( $path, $render ) ) {
			register_block_type_from_metadata(
				__DIR__ . $path,
				array(
					'render_callback' => function ( $attributes, $content, $block ) use ( $path, $render ) {
						require_once ABSPATH . WPINC . '/blocks' . $path . '.php';
						return call_user_func( $render, $attributes, $content, $block );
					},
				)
			);
		}
	}
);

// This file was autogenerated by tools/release/sync-stable-blocks.js, do not change manually!
// Requires files for dynamic blocks necessary for core blocks registration.
require_once ABSPATH . WPINC . '/blocks/calendar.php';
require_once ABSPATH . WPINC . '/blocks/categories.php';
require_once ABSPATH . WPINC . '/blocks/comment-author-name.php';
require_once ABSPATH . WPINC . '/blocks/comment-content.php';
require_once ABSPATH . WPINC . '/blocks/comment-date.php';
require_once ABSPATH . WPINC . '/blocks/comment-edit-link.php';
require_once ABSPATH . WPINC . '/blocks/comment-reply-link.php';
require_once ABSPATH . WPINC . '/blocks/comment-template.php';
require_once ABSPATH . WPINC . '/blocks/comments.php';
require_once ABSPATH . WPINC . '/blocks/comments-pagination.php';
require_once ABSPATH . WPINC . '/blocks/comments-pagination-next.php';
require_once ABSPATH . WPINC . '/blocks/comments-pagination-numbers.php';
require_once ABSPATH . WPINC . '/blocks/comments-pagination-previous.php';
require_once ABSPATH . WPINC . '/blocks/comments-title.php';
require_once ABSPATH . WPINC . '/blocks/cover.php';
require_once ABSPATH . WPINC . '/blocks/file.php';
require_once ABSPATH . WPINC . '/blocks/footnotes.php';
require_once ABSPATH . WPINC . '/blocks/gallery.php';
require_once ABSPATH . WPINC . '/blocks/home-link.php';
require_once ABSPATH . WPINC . '/blocks/image.php';
require_once ABSPATH . WPINC . '/blocks/latest-comments.php';
require_once ABSPATH . WPINC . '/blocks/latest-posts.php';
require_once ABSPATH . WPINC . '/blocks/navigation.php';
require_once ABSPATH . WPINC . '/blocks/navigation-link.php';
require_once ABSPATH . WPINC . '/blocks/navigation-submenu.php';
require_once ABSPATH . WPINC . '/blocks/page-list.php';
require_once ABSPATH . WPINC . '/blocks/page-list-item.php';
require_once ABSPATH . WPINC . '/blocks/post-comments-form.php';
require_once ABSPATH . WPINC . '/blocks/post-excerpt.php';
require_once ABSPATH . WPINC . '/blocks/post-featured-image.php';
require_once ABSPATH . WPINC . '/blocks/post-template.php';
require_once ABSPATH . WPINC . '/blocks/post-terms.php';
require_once ABSPATH . WPINC . '/blocks/query.php';
require_once ABSPATH . WPINC . '/blocks/query-title.php';
require_once ABSPATH . WPINC . '/blocks/search.php';
require_once ABSPATH . WPINC . '/blocks/shortcode.php';
require_once ABSPATH . WPINC . '/blocks/site-logo.php';
require_once ABSPATH . WPINC . '/blocks/social-link.php';
require_once ABSPATH . WPINC . '/blocks/template-part.php';
